
import { Listing, Vendor, ListingType } from './types';

export const MOCK_VENDORS: Vendor[] = [
    {
        id: 1,
        name: 'Emporio "El Cobre"',
        logo: 'https://picsum.photos/seed/emporio/100/100',
        description: 'Pequeña Pyme familiar dedicada a la venta de productos gourmet locales y artesanías de la región de Antofagasta.',
        rating: 4.8,
        reviews: 124,
        isVerified: true,
    },
    {
        id: 2,
        name: 'Servicios Rápidos "La Portada"',
        logo: 'https://picsum.photos/seed/servicios/100/100',
        description: 'Ofrecemos soluciones rápidas para el hogar: gasfitería, electricidad y reparaciones menores. ¡Confianza y calidad!',
        rating: 4.5,
        reviews: 88,
        isVerified: true,
    },
    {
        id: 3,
        name: 'Comunidad de Trueque "Mano a Mano"',
        logo: 'https://picsum.photos/seed/trueque/100/100',
        description: 'Un espacio para intercambiar objetos y habilidades sin dinero de por medio. Fomentamos la economía circular y el apoyo mutuo.',
        rating: 5.0,
        reviews: 210,
        isVerified: false,
    },
    {
        id: 4,
        name: 'Juanita - Ventas de Garaje',
        logo: 'https://picsum.photos/seed/vecina/100/100',
        description: '¡Hola! Soy Juanita, vecina del sector centro. Vendo cositas que ya no uso pero que están en perfecto estado. ¡Una segunda vida para todo!',
        rating: 4.9,
        reviews: 22,
        isVerified: false,
    },
];

const now = new Date();

export const MOCK_LISTINGS: Listing[] = [
    {
        id: 1,
        vendorId: 1,
        title: 'Aceite de Oliva Artesanal',
        description: 'Exquisito aceite de oliva extra virgen, producido en el valle cercano. Ideal para ensaladas y cocina gourmet.',
        type: ListingType.Product,
        location: { lat: -23.65, lng: -70.40 },
        image: 'https://picsum.photos/seed/aceite/400/300',
        price: 12000,
        createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        status: 'active',
    },
    {
        id: 2,
        vendorId: 1,
        title: 'Artesanía en Cobre',
        description: 'Figuras decorativas hechas a mano por artesanos locales, representando la cultura del norte.',
        type: ListingType.Product,
        location: { lat: -23.645, lng: -70.395 },
        image: 'https://picsum.photos/seed/cobre/400/300',
        price: 25000,
        createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        status: 'active',
    },
    {
        id: 3,
        vendorId: 2,
        title: 'Reparación de Enchufes',
        description: 'Servicio rápido y seguro para reparación e instalación de enchufes en tu hogar.',
        type: ListingType.Service,
        location: { lat: -23.63, lng: -70.39 },
        image: 'https://picsum.photos/seed/enchufe/400/300',
        price: 15000,
        createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        status: 'active',
    },
     {
        id: 4,
        vendorId: 2,
        title: 'Gasfitería de Emergencia',
        description: 'Atendemos urgencias de gasfitería 24/7. Fugas, destapes y más.',
        type: ListingType.Service,
        location: { lat: -23.66, lng: -70.41 },
        image: 'https://picsum.photos/seed/gasfiteria/400/300',
        price: 30000,
        createdAt: new Date().toISOString(),
        status: 'active',
    },
    {
        id: 5,
        vendorId: 3,
        title: 'Intercambio Guitarra por Bicicleta',
        description: 'Ofrezco guitarra acústica en excelente estado, busco bicicleta de montaña aro 26 o similar.',
        type: ListingType.Barter,
        location: { lat: -23.652, lng: -70.405 },
        image: 'https://picsum.photos/seed/guitarra/400/300',
        price: 0,
        createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        status: 'active',
    },
    {
        id: 6,
        vendorId: 3,
        title: 'Busco clases de inglés',
        description: 'Ofrezco clases de matemáticas a cambio de clases de inglés conversacional.',
        type: ListingType.Barter,
        location: { lat: -23.638, lng: -70.402 },
        image: 'https://picsum.photos/seed/clases/400/300',
        price: 0,
        createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        status: 'active',
    },
    {
        id: 7,
        vendorId: 4,
        title: 'Lote Ropa de Bebé (niña)',
        description: 'Vendo lote de ropa para bebé de 0 a 6 meses, en excelente estado. Poca usada, marcas variadas. Ideal para nueva mamá.',
        type: ListingType.GarageSale,
        location: { lat: -23.642, lng: -70.398 },
        image: 'https://picsum.photos/seed/ropabebe/400/300',
        price: 20000,
        createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        status: 'active',
    },
    {
        id: 8,
        vendorId: 4,
        title: 'Juguera Oster Clásica',
        description: 'Juguera Oster en perfecto funcionamiento. Vaso de vidrio, ideal para batidos y jugos. La vendo por renovación.',
        type: ListingType.GarageSale,
        location: { lat: -23.643, lng: -70.399 },
        image: 'https://picsum.photos/seed/juguera/400/300',
        price: 18000,
        createdAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        status: 'active',
    }
];

export const ANTOFAGASTA_COORDS = { lat: -23.65, lng: -70.4 };
